pool:
  vmImage: 'Ubuntu 16.04'

steps:
- bash: 'uname -a'
  displayName: uname

- bash: cpuinfo
  displayName: cat /proc/cpuinfo

- bash: nproc
  displayName: nproc

- bash: gcc
  displayName: gcc -v