pool:
  vmImage: 'win1803'

steps:
- task: PowerShell@2
  displayName: 'What environment variables do we have?'
  inputs:
    targetType: 'inline'
      script: gci Env: | %{write-host "$($_.Key): $($_.Value)" }
      
      write-output "Finished update?"

