pool:
  vmImage: 'win1803'

steps:
- task: PowerShell@2
  displayName: 'What environment variables do we have?'
  inputs:
    targetType: 'inline'
    script: 'gci Env: | %{write-host "$($_.Key): $($_.Value)" }'

- task: PowerShell@2
  displayName: 'Passing an environment variable to bash, maybe'
  inputs:
    targetType: 'inline'
    script: 'bash -lc "echo bash says that AGENT_MACHINENAME is $AGENT_MACHINENAME" '

- task: PowerShell@2
  displayName: 'What variables are inside of bash?'
  inputs:
    targetType: 'inline'
    script: 'bash -lc "export"'
